version: '3.8'
services:
  dynamodb-climapush:
    command: "-jar DynamoDBLocal.jar"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-climapush
    ports:
      - "8000:8000"
    working_dir: /home/dynamodblocal
